config/routes.rb
Forward::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  resources :sessions, :only => [:new,:create,:destroy]
  resources :users, :only =>[:edit,:update]

  resources :messages, :only => [:new,:create]

  resources :locales, :only => [:create]
  resources :translations, :only => [:index,:create] do
    collection do
      delete 'delete'
    end
  end

  namespace "procmail" do
    resources :filters
  end
  match 'procmail', :controller => "procmail/filters", :action => "index"

  namespace "forward" do
  end

  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'welcome'  => 'sessions#new'
  
  match 'forward/edit' => 'operator#edit'
  match 'forward/connect'  => 'operator#connect'
  match 'forward/update'   => 'operator#update'
  get "operator/edit"
  post "operator/connect"
  post "operator/update"
  root :to => "sessions#new"
end

app/models/translation.rb
class Translation < ActiveRecord::Base
  belongs_to :locale

  attr_accessible :locale_id, :key, :value

  validates_presence_of :key, :value, :locale_id

  def initialize_from_redis(key)
    self.locale = Locale.find_by_title(key.split('.')[0..-2].join('.'))
    self.key = key.split('.')[-1]
    self.value = I18n.t(key.split('.')[1..-1].join('.'))
    self
  end
end

# == Schema Information
#
# Table name: translations
#
#  id         :integer(4)      not null, primary key
#  locale_id  :integer(4)
#  key        :string(255)
#  value      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  load_and_authorize_resource

  def index
    @translation = params[:key].blank? ? Translation.new : Translation.new.initialize_from_redis(params[:key])
    @translations = $redis 
    @locales = Locale.all
    @locale = params[:locale].blank? ? Locale.new : Locale.find_by_title(params[:locale].split('.')[0..-2].join('.'))
  end

  def create
    @translation = Translation.new(params[:translation])
    if @translation.valid?
      locale = @translation.locale
      I18n.backend.store_translations(@translation.locale.title, {@translation.key => @translation.value}, :escape => false)
      redirect_to translations_url, :notice => added(:translation)
    else
      @translations = $redis
      @locales = Locale.all
      @locale = Locale.new
      render :index
    end
  end

  def delete
    $redis.del(params[:key])
    redirect_to translations_path
  end
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/translations/index.html.erb
<%= content_for(:container) do %>widest<% end %>
<% content_for(:login) do %><%= link_to t(:logout), logout_path %><% end %>

<div id="main">
  <h1><%= pl(:translation) %></h1>

  <div class="table small_font">
    <% @translations.keys.reject{|e| e =~ /content_key/}.sort_by{|e| locale(e)}.each do |key| %>
      <div class="outer">
        <div class="inner">
          <span class="bold w398 truncate"><%= key %></span>
          <span class="w300 truncate"><%= t key[3..-1] %></span>
          <span class="action"><%= link_to t(:edit), translations_path(:key => key) %></span>
          <span class="action"><%= link_to t(:del), delete_translations_path(:key => key), :confirm => sure?, :method => :delete %></span>
          <div class="clear"></div>
        </div>
      </div>
    <% end %>
  </div>

  <h1><%= add(:translation) %></h1>

  <%= semantic_form_for @translation, :html => {:class => "normal"} do |f| %>
    <%= f.input :locale, :as => :select, :collection => @locales %>
    <%= f.input :key %>
    <%= f.input :value %>
    <%= f.submit (@translation.key.blank? ? create(:translation) : update(:translation)), :class => :submit %>
  <% end %>
  <div class="clear"></div>

  <h1><%= add(:locale) %></h1>

  <%= semantic_form_for @locale, :html => {:class => "normal"} do |f| %>
    <%= f.input :title %>
    <%= f.submit (@locale.new_record? ? create(:locale) : update(:locale)), :class => :submit %>
  <% end %>
  <div class="clear"></div>

  <div class="flash">
    <div id="flash_container" class="admin_width_with_margin">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
    </div>
  </div>
  <div class="clear"></div>
</div>