config/routes.rb
Forward::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  resources :sessions, :only => [:new,:create,:destroy]
  resources :users, :only =>[:edit,:update]

  resources :messages, :only => [:new,:create]

  resources :locales, :only => [:create]
  resources :translations, :only => [:index,:create] do
    collection do
      delete 'delete'
    end
  end

  namespace "procmail" do
    resources :filters
  end
  match 'procmail', :controller => "procmail/filters", :action => "index"

  namespace "forward" do
  end

  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'welcome'  => 'sessions#new'
  
  match 'forward/edit' => 'operator#edit'
  match 'forward/connect'  => 'operator#connect'
  match 'forward/update'   => 'operator#update'
  get "operator/edit"
  post "operator/connect"
  post "operator/update"
  root :to => "sessions#new"
end

app/controllers/operator_controller.rb
# -*- coding: utf-8 -*-
#require 'rpam'

class OperatorController < ApplicationController
  #include Rpam

  def login
  end

  def logout
    session[:username] = nil
    session[:password] = nil
    redirect_to login_path, :notice => notify(:logged_out)
  end
  
  def connect
    if params[:username].blank? || params[:password].blank?
      flash[:alert] = alert2(:incorrect,t('messages.or',:obj1=>ft(:username),:obj2=>ftd(:password)))
      redirect_to login_path and return
    end
    if authpam(params[:username],params[:password])
      session[:username] = params[:username]
      session[:password] = params[:password]
      redirect_to forward_edit_path, :notice => notify(:logged_in)
    else
      redirect_to login_path, :alert => alert2(:incorrect,
        t('messages.or',:obj1=>ft(:username),:obj2=>ftd(:password)))
    end
  end

  def edit
    if session[:username]
      if params[:address]
        if params[:commit] == add(:address_field)
          @input = params[:address].merge({ params[:address].keys.reject{|e| e=="keep"}.length.to_s => ""})
        else
          @input = params[:address]
        end
      else
        IO.popen("/usr/local/sbin/chfwd -g #{session[:username]}", 'r+') do |pipe|
          pipe.write(session[:password])
          pipe.close_write
          @input = convert_in(pipe.read) 
        end
      end
    else
      redirect_to login_path, :alert => alert(:unauthorized_access)
    end
  end

  def update
    if params[:commit] == add(:address_field)
      flash[:notice] = added(:address_field)
      redirect_to forward_edit_path(:commit => add(:address_field), :no => address_field_no, :address => params[:address])
    else
      IO.popen("/usr/local/sbin/chfwd -s #{session[:username]}", 'r+') do |pipe|
        pipe.write "#{session[:password]}\n"
        pipe.write "\\#{session[:username]}\n" if params["address"]["keep"] == "yes"
        pipe.write "#{params[:address].values.reject{|e| e.blank? || e=="yes"}.join("\n")}\n"
        pipe.close_write
      end
      flash[:notice] = updated(:forwarding_address)
      redirect_to forward_edit_path
    end
  end

  def procmail
    @filter = Filter.new
    @filter.rules.build
    @filter.actions.build
  end

  private
    def address_field_no; params[:address].length end
    def authpam(user,pass); pass == "correct" ? true : false end
    def convert_in(s,d=5)
      ret = {} 
      adds = s.split("\n").map{|line| line.split(',').map(&:strip)}.flatten
      keep = nil
      adds.each_with_index do |add,i|
        keep = adds.delete_at(i) if add[0] == "\\"
      end
      adds.each_with_index do |add,i|
        ret[i.to_s] = add.chomp
      end
      (d-adds.length).times do |i|
        ret[(i+adds.length).to_s] = ""
      end
      ret["keep"] = keep.nil? ? nil : "yes"
      ret
    end
    def inc_address_field_no; params[:no].to_i+1 end
end

app/helpers/operator_helper.rb
module OperatorHelper
end

app/views/operator/_address_field.html.erb
<%= label_tag "address[#{no}]".to_sym, t(:address,:no=>no.to_i+1) %>
<%= text_field_tag "address[#{no}]", value, :class => :w300 %>

app/views/operator/edit.html.erb
<%= content_for(:container) do %>wider<% end %>
<% content_for(:login) do %><%= link_to t(:logout), logout_path %><% end %>

<div id="main">
  <h1><%= t(:mail_forward_settings_for,:user=>session[:username]) %></h1>

  <%= form_tag forward_update_path, :id => "address_edit", :class => :normal do %>
    <% @input.each do |key, value| %>
      <% if key != "keep" %>
        <p><%= render "address_field", :no => key, :value => value %></p>
      <% end %>
    <% end %>
    <%# link_to_add_fields add(:address_field) %>
    <p class="box_plus_button">
      <%= label_tag "address[keep]", ft(:keep_a_copy), :class => %w(w200 f14 ta-left) %>
      <%= check_box_tag "address[keep]", 'yes', @input["keep"], :class => :checkbox %>
      <%= submit_tag add(:address_field), :class => :submit, :id => :add %>
      <div class="clear"></div>
    </p>
    <div class="flash_plus_button">
      <div id="flash_container">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
      </div>
      <%= submit_tag t(:update), :class => :submit, :id => :update %>
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
  <% end %>
</div>

app/views/operator/login.html.erb
<div id="main">
  <h1><%= t(:mail_forward_login) %></h1>

  <%= form_tag connect_path, :class => :normal do %>
  <p>
    <%= label_tag :username, ft(:username) %>
    <%= text_field_tag :username %>
    <div class="clear"></div>
  </p>
  <p>
    <%= label_tag :password, ft(:password) %>
    <%= password_field_tag :password %>
    <div class="clear"></div>
  </p>
  <div class="flash_plus_button">
    <div id="flash_container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
    </div>
    <%= submit_tag t(:login), :class => :submit %>
  </div>
  <div class="clear"></div>
  <% end %>
</div>