config/routes.rb
Forward::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  resources :sessions, :only => [:new,:create,:destroy]
  resources :users, :only =>[:edit,:update]

  resources :messages, :only => [:new,:create]

  resources :locales, :only => [:create]
  resources :translations, :only => [:index,:create] do
    collection do
      delete 'delete'
    end
  end

  namespace "procmail" do
    resources :filters
  end
  match 'procmail', :controller => "procmail/filters", :action => "index"

  namespace "forward" do
  end

  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'welcome'  => 'sessions#new'
  
  match 'forward/edit' => 'operator#edit'
  match 'forward/connect'  => 'operator#connect'
  match 'forward/update'   => 'operator#update'
  get "operator/edit"
  post "operator/connect"
  post "operator/update"
  root :to => "sessions#new"
end

app/models/filter.rb
class Filter < ActiveRecord::Base
  include Procmail

  belongs_to :user

  has_many :rules, :dependent => :destroy
  accepts_nested_attributes_for :rules, :allow_destroy => true

  has_many :actions, :dependent => :destroy
  accepts_nested_attributes_for :actions, :allow_destroy => true

  validate :at_least_one_action_must_exist
  validate :at_least_one_rule_must_exist

  MATCH_ALL = "match_all"
  MATCH_ANY = "match_any"
  GLUES = [MATCH_ALL, MATCH_ANY]

  def contents; [rules.map(&:contents), actions.map(&:contents)] end

  def actions_contents; actions.map(&:contents) end
  def actions_to_file
    if actions.count <= 1
      actions.first.to_file
    else
      ret = []
      actions.sort.each do |action|
        ret << action.multiple_action_to_file(actions.sort.last==action)
      end
      "{\n"+ret.join("\n\n")+"\n}"
    end
  end
  def action 
    raise Exception, "Referring to 'the action' but there are many." if first_action != last_action
    first_action
  end
  def action_destination; action.destination end
  def actions_to_s; actions.map(&:to_s) end

  def first_action; actions.first end
  def first_rule; rules.first end
  def first_rules_contents; first_rule.contents end

  def section?(section)
    rules.map(&section).include?(true)
  end
  def japanese_cc?; section?(:japanese_cc?) end
  def japanese_sender?; section?(:japanese_sender?) end
  def japanese_subject?; section?(:japanese_subject?) end
  def japanese_recipient?; section?(:japanese_recipient?) end
  def japanese_to_or_cc?; section?(:japanese_to_or_cc?) end

  def last_action; actions.last end
  def last_rule; rules.last end 
  def last_rules_contents; last_rule.contents end
  def rule
    raise Exception, "More than one rule." if first_rule != last_rule
    first_rule
  end
  def rule_contents; rule.contents end
  def rule_section; rule.section end
  def rules_contents; rules.map(&:contents) end
  def rules_to_file
    if glue == "and"
      rules.map(&:to_file).join("\n") 
    elsif rules_section_is_unique?
      if rules_include_japanese? 
        ret = "*#{first_rule.beginning_to_file_in_japanese}"
        ret + "(#{rules.map(&:end_to_file_in_japanese).join('|')})"
      else
        ret = "*#{first_rule.beginning_to_file_in_english}"
        ret + "(#{rules.map(&:end_to_file_in_english).join('|')})"
      end
    elsif rules_include_japanese? #and are more than one
      rules.map{|e| "* ! #{e.beginning_to_file.lstrip}#{e.end_to_file}"}.join("\n")
    else
      "*#{rules.map(&:to_s).join('|')}"
    end
  end
  def rules_to_s; rules.map(&:to_s) end

  def to_file
    ret = ":0"
    if one_action? and copy_message?
      ret += "c" unless de_morgan?
    end
    if one_action? and move_message_to_folder?
      ret += ":" unless de_morgan?
    end
    ret += "\n"+rules_to_file+"\n"
    if de_morgan? and glue == "or"
      ret += "{ }\n:0E" 
      ret += "c" if one_action? and copy_message?
      ret += ":" if one_action? and move_message_to_folder?
      ret += "\n"
    end
    ret += actions_to_file unless actions.empty?
    ret
  end

  class << self
    def glues; GLUES.map{|e| I18n.t("filters.glues.#{e}")}.zip(["and","or"]) end
  end

  private

    def at_least_one_action_must_exist
      errors.add(:base, "At least one action must exist.") if actions.empty? unless Rails.env == "test"
    end
    def at_least_one_rule_must_exist
      errors.add(:base, "At least one rule must exist.") if rules.empty? unless Rails.env == "test"
    end

    def copy_message?; actions.first.copy_message? end
    def de_morgan?
      !rules_section_is_unique? and rules_include_japanese?
    end
    def forward_message?; actions.first.forward_message? end
    def move_message_to_folder?; first_action.move_message_to_folder? end
    def one_action?; actions.count == 1 end
    def rules_section_is_unique?; rules.map(&:section).uniq.size == 1 end
    def rules_include_japanese?
      rules.map(&:substance_is_english?).include?(nil)
    end
end




# == Schema Information
#
# Table name: filters
#
#  id         :integer(4)      not null, primary key
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer(4)
#  glue       :string(255)     default("and")
#

app/controllers/procmail/filters_controller.rb
class Procmail::FiltersController < ApplicationController
  include Forwarding
  include Procmail

  before_filter :build_user_filter_with_params, :only => :create
  before_filter :check_existence_of_filter, :only => [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def show
    redirect_to edit_procmail_filter_path(@filter)
  end

  def deliver_error(e)
    @error = "You have encounted an error.<br><br>#{e}<br><br>The administrator has been informed.<br>Please wait while the problem is being resolved."
    ErrorMailer.filter_error(session[:username],e).deliver
  end

  def index
    redirect_to new_procmail_filter_path and return if params[:filter].present?
    begin
      prepare_filters(session[:username], session[:password])
    rescue Exception => e
      deliver_error(e)
    end
    session[:prolog] = "#{@prolog.join("\n")}" if @prolog
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @filters }
    end
  end

  def new
    @filter.rules.build
    @filter.actions.build
  end

  def create
    redirect_to procmail_filters_path and return if params[:cancel] 
    if params[:rule_plus] or params[:action_plus]
      build_added_rule
      build_added_action
      render :new and return
    end
    delete_button = params.keys.select{|e| e.match(/minus/)}.join
    if delete_button.present?
      delete_attr = delete_button.split('_')[0]
      delete_index = delete_button.split('_')[-1].to_i
      if delete_attr == "rule"
        @filter.rules.delete_at(delete_index)
      else
        @filter.actions.delete_at(delete_index)
      end
      @filter.rules.build if @filter.rules.empty?
      @filter.actions.build if @filter.actions.empty?
      render :edit and return
    end

    @filter.actions.inspect
    if @filter.save
      save_filters(session[:username], session[:password], session[:prolog], current_user.filters)
      update_forwards(session[:username], session[:password])
      redirect_to procmail_filters_path, :notice => created(:filter)
    elsif @filter.rules.map(&:valid?).reject{|e| e==false}.empty?
      @filter.rules.build if @filter.rules.empty?
      @filter.actions.build if @filter.actions.empty?
      render :new
    elsif @filter.actions.map(&:valid?).reject{|e| e==false}.empty?
      @filter.rules.build if @filter.rules.empty?
      @filter.actions.build if @filter.actions.empty?
      render :new
    else
      @filter.rules.reject!{|e| !e.valid?}
      @filter.actions.reject!{|e| !e.valid?}
      @filter.save
      save_filters(session[:username], session[:password], session[:prolog], current_user.filters)
      update_forwards(session[:username], session[:password])
      flash[:notice] = "Created rules: #{@filter.rules.count}, actions: #{@filter.actions.count}"
      redirect_to procmail_filters_path
    end
  end

  def edit
    build_non_saved_rules
    build_added_rule
    build_non_saved_actions
    build_added_action
  end

  def update
    redirect_to procmail_filters_path and return if params[:cancel] 
    @filter.actions.inspect
    @filter.attributes = params[:filter]
    if params[:rule_plus] or params[:action_plus]
      build_added_rule
      build_added_action
      render :edit and return
    end
    delete_button = params.keys.select{|e| e.match(/minus/)}.join
    if delete_button.present?
      delete_attr = delete_button.split('_')[0]
      delete_index = delete_button.split('_')[-1]
      if delete_attr == "rule"
        delete_rule = params[:filter][:rules_attributes].delete(delete_index)
        @filter.rules.delete_at(delete_index.to_i)
        Rule.find(delete_rule[:id].to_i).destroy if delete_rule[:id]
      else
        delete_action = params[:filter][:actions_attributes].delete(delete_index)
        @filter.actions.delete_at(delete_index.to_i)
        Action.find(delete_action[:id].to_i).destroy if delete_action[:id]
      end
      @filter.rules.build if @filter.rules.empty?
      @filter.actions.build if @filter.actions.empty?
      render :edit and return
    end
    
    if @filter.save 
      #@filter.update_attributes(params[:filter])
      filter = Filter.find(params[:id])
      if filter.rules.empty? || filter.actions.empty? 
        filter.destroy
        flash[:notice] = removed(:filter)
      end
      save_filters(session[:username], session[:password], session[:prolog], current_user.filters)
      redirect_to procmail_filters_path
    else
      if @filter.actions.map(&:valid?).reject{|e| e==false}.empty?
        render :edit
      elsif @filter.rules.map(&:valid?).reject{|e| e==false}.empty?
        render :edit
      else
        @filter.actions.reject!{|e| !e.valid?}
        @filter.rules.reject!{|e| !e.valid?}
        @filter.save
        save_filters(session[:username], session[:password], session[:prolog], current_user.filters)
        flash[:notice] = "Updated rules: #{@filter.rules.count}, actions: #{@filter.actions.count}"
        redirect_to procmail_filters_path
      end
    end
  end

  def destroy
    @filter.destroy
    save_filters(session[:username], session[:password], session[:prolog], current_user.filters)
    redirect_to procmail_filters_path
  end

  private

    def build_added_action; @filter.actions.build if params[:action_plus] end
    def build_added_rule; @filter.rules.build if params[:rule_plus] end
    def build_non_saved_associations(assoc)
      if params["filter"] && params["filter"]["#{assoc}_attributes"] 
        params["filter"]["#{assoc}_attributes"].each do |key,value|
          if value[:id].nil?
            @filter.send(assoc).build(value)
          else
            @filter.send(assoc).select{|e| e.id==key.to_i}
          end
        end
      end
    end
    def build_non_saved_actions; build_non_saved_associations(:actions) end
    def build_non_saved_rules; build_non_saved_associations(:rules) end
    def build_user_filter_with_params; @filter = current_user.filters.build(params[:filter]) if current_user end

    def check_existence_of_filter
      redirect_to procmail_filters_path and return unless Filter.exists?(params[:id])
    end
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/views/procmail/filters/_error.html.erb
<h1>Error</h1>

<div class="margin-left">
  <%= raw @error %>
</div>

<div class="flash">
  <div id="flash_container" class="admin_width_with_margin">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
  </div>
</div>
<div class="clear"></div>

app/views/procmail/filters/_form.html.erb
<%= content_for(:container) do %>widerer<% end %>
<% content_for(:login) do %><%= link_to t(:logout), logout_path %><% end %>

<div id="main">
  <% content_for(:site_nav) do %>
    <%= link_to t(:logout), logout_path, :class => :right %>
  <% end %>

  <h1><%= either_of(@filter.new_record?,new(:filtering_rule),edit(:filtering_rule)) %></h1>


  <%= semantic_form_for [:procmail, @filter], :html =>{:id => :filter} do |f| %>
    <%= f.semantic_errors %>
    <h2 class="margin-left"><%= t(:condition) %></h2>
    <%= f.input :glue, :as => :radio, :collection => Filter.glues, :label => false, :wrapper_html => {:class => "inline margin-left small_font"} %>
    <div class="clear"></div>
    <% @filter.rules.each_with_index do |rule,i| %>
      <%= f.inputs :for => [:rules, rule], :class => "inline margin-left compact", :id => :rules do |ref| %>
        <%= render 'rules/form', :f => ref, :i => i %>
      <% end %>
    <% end %>
    <%= f.submit add(:rule), :class => "submit inner", :name => "rule_plus" %>
    <div class="clear"></div>
    <div class="hr"></div>
    <h2 class="margin-left"><%= t(:action) %></h2>
    <h3 class="margin-left"><%= mess(:perform_these_actions) %></h3>
    <% @filter.actions.each_with_index do |action,i| %>
      <%= f.inputs :for => [:actions, action], :class => "inline margin-left compact", :id => :actions do |ref| %>
        <%= render 'actions/form', :f => ref, :i => i %>
      <% end %>
    <% end %>
    <%= f.submit add(:action), :class => "submit inner", :name => "action_plus" %>
    <div class="clear"></div>
    <div class="flash_plus_button">
      <div id="flash_container">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
      </div>
      <%= f.submit either_of(@filter.new_record?, t(:create), t(:update)), :class => "submit outer" %>
      <%= f.submit t(:cancel), :class => "submit outer", :name => :cancel %>
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
  <% end %>
</div>

app/views/procmail/filters/_index.html.erb
<h1><%= t(:mail_filter_settings_for, :user=>session[:username]) %></h1>

<div class="table r4" id="filters">
  <% @filters.each_with_index do |filter,no| %>
    <div class="outer">
      <% i=0 %>
      <% while i < [filter.rules.count, filter.actions.count].max %>
        <div class="inner">
          <span class="w25">
            <%= "#{no+1}." if i==0 %>
          </span>
          <span class="w373 truncate">
            <% if filter.rules.count > i %>
              <% if filter.rules.count == 1 %>
                <%= rule_sentence("start", filter.rules[i]) %>
              <% elsif i==0 and filter.glue == "or" %>
                <%= rule_sentence("start_or", filter.rules[i]) %>
              <% elsif i==0 and filter.glue == "and" %>
                <%= rule_sentence("start_and", filter.rules[i], true) %>
              <% elsif filter.rules.count-1 == i and filter.glue == "or" %>
                <%= rule_sentence("end_or", filter.rules[i]) %>
              <% elsif filter.rules.count-1 == i and filter.glue == "and" %>
                <%= rule_sentence("end_and", filter.rules[i]) %>
              <% elsif filter.glue == "or" %>
                <%= rule_sentence("or", filter.rules[i]) %>
              <% elsif filter.glue == "and" %>
                <%= rule_sentence("and", filter.rules[i], true) %>
              <% end %>
            <% end %>
          </span>
          <span class="w300 truncate">
            <%= t(:action_sentence, :operation => t("actions.operations."+filter.actions[i].operation), :destination => filter.actions[i].destination ) if filter.actions.count > i %>
          </span>
          <span class="action">
            <%= link_to t(:edit), edit_procmail_filter_path(filter) if can?(:edit, filter) && i==0 %>
          </span>
          <span class="action">
            <%= link_to t(:del), procmail_filter_path(filter), :confirm => sure?, :method => :delete if can?(:destroy, filter) && i==0 %>
          </span>
          <% i+=1 %>
          <div class="clear"></div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div id="bottom_links">
  <%= link_to new(:filtering_rule), new_procmail_filter_path, :class => "left-margin small-font" %>
</div>

<div class="flash">
  <div id="flash_container" class="admin_width_with_margin">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
  </div>
</div>

<div class="clear"></div>

app/views/procmail/filters/edit.html.erb
<%= render 'form' %>

app/views/procmail/filters/index.html.erb
<%= content_for(:container) do %>widest<% end %>
<% content_for(:login) do %><%= link_to t(:logout), logout_path %><% end %>

<div id="main">
  <% content_for(:site_nav) do %>
    <%= link_to t(:logout), logout_path, :class => :right %>
  <% end %>

  <% if @error %>
    <%= render 'error' %>
  <% else %>
    <%= render 'index' %>
  <% end %>
</div>

app/views/procmail/filters/new.html.erb
<%= semantic_form_for @filter, :url => procmail_path, :html => {:id => "new_rule"} do |f| %>
  <%= f.semantic_fields_for :rules do |ref| %>
    <%= render 'rules/form', :f => ref %>
  <% end %>
<% end %>

<%= semantic_form_for @filter, :url => procmail_path, :html => {:id => "new_action"} do |f| %>
  <%= f.semantic_fields_for :actions do |ref| %>
    <%= render 'actions/form', :f => ref %>
  <% end %>
<% end %>