config/routes.rb
Forward::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  resources :sessions, :only => [:new,:create,:destroy]
  resources :users, :only =>[:edit,:update]

  resources :messages, :only => [:new,:create]

  resources :locales, :only => [:create]
  resources :translations, :only => [:index,:create] do
    collection do
      delete 'delete'
    end
  end

  namespace "procmail" do
    resources :filters
  end
  match 'procmail', :controller => "procmail/filters", :action => "index"

  namespace "forward" do
  end

  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'welcome'  => 'sessions#new'
  
  match 'forward/edit' => 'operator#edit'
  match 'forward/connect'  => 'operator#connect'
  match 'forward/update'   => 'operator#update'
  get "operator/edit"
  post "operator/connect"
  post "operator/update"
  root :to => "sessions#new"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? "#{yield(:title)} - " : "" %>Forward</title>
  <title>Forward</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf8" />
  <%= stylesheet_link_tag 'screen.css', :media => 'screen, projection' %>
  <%= stylesheet_link_tag 'print.css', :media => 'print' %>
  <!--[if lt IE 8]>
  <%= stylesheet_link_tag 'ie.css', :media => 'screen, projection' %>
  <![endif]-->
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "jquery", "rails", "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="header">
  <%# image_tag 'witch.gif' %>
</div>
<div id="contents_container" class="<%= yield(:container) %>">
  <div id="main_container">
    <div id="site_nav">
      <div id="language">
        <% if english? %>
          <%= link_to "日本語", :language => 'ja', :address => @input, :filter => @filter.to_s %>
        <% else %>
          <%= link_to "English", :language => 'en', :address => @input, :filter => @filter.to_s %>
        <% end %>
      </div>
      <% unless yield(:no_navigation) == "true" %>
        <div id="navigation">
          <%= link_to t(:mail_forwarding), forward_edit_path, :class => request.path =~ /forward/ ? :active : "" %>
          <%= link_to t(:mail_filtering), procmail_filters_path, :class => request.path =~ /procmail/ ? :active : "" %>
          <%= link_to pl(:translation), translations_path, :class => request.path =~ /translations/ ? :active : "" if can? :index, Translation %>
        </div>
      <% end %>
      <div id="login">
        <%= yield(:login) %>
      </div>
    </div>
    <%= yield %>
  </div>
  <div id="footer">
    <%# link_to t(:flexible_information_system_research_center), new_message_path %>
    <%= t(:flexible_information_system_research_center) %>
    <%= t(:tel) %>: 5079
  </div>
</div>
</body>
</html>